accounts/urls.py
from django.urls import path
from .views import login, logout, signup

urlpatterns = [
  path('login/', login, name='login'),
  path('logout/', logout, name='logout'),
  path('signup/', signup, name='signup'),
]

django_practice/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import main
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name="main"),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('lovely/', include('lovely.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

lovely/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import main, new, create, delete

app_name = "lovely"
urlpatterns = [
  path('', main, name="main"),
  path('new/', new, name="new"),
  path('create/', create, name="create"),
  path('delete/', delete, name="delete"),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .views import main, new, create, show, edit, update, delete


app_name = 'posts'
urlpatterns = [
  path('', main, name="main"),
  path('new/', new, name="new"),
  path('create/', create, name="create"),
  path('<int:post_id>/', show, name="show"),
  path('edit/<int:post_id>/', edit, name="edit"),
  path('update/<int:post_id>/', update, name="update"),
  path('delete/<int:post_id>/', delete, name="delete"),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

lovely/models.py
from django.db import models
from templates.shared.timestamped import TimeStampedModel
from django.utils.translation import ugettext_lazy as _

class Lovely(TimeStampedModel):
  image = models.ImageField(_("이미지"), upload_to="lovely/img/", default="lovely/default/photo.png", null=False)

maps/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.urls import reverse
from users.models import User
from django.utils.translation import ugettext_lazy as _
from templates.shared.timestamped import TimeStampedModel


class Post(TimeStampedModel):
    class Meta:
        ordering = ['-created_at']

    POST_TYPES = [
        (0, "칼럼"),
        (1, "뉴스"),
        (2, "소설"),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="사용자")
    title = models.CharField(_("제목"), max_length=50)
    content = models.TextField(_("내용"))
    view_count = models.IntegerField(_("조회수"), default=0)
    _type = models.PositiveSmallIntegerField(_("게시글 타입"), choices=POST_TYPES)
    image = models.ImageField(_("게시글"), upload_to='posts/img', default="posts/default/dgu.png")


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:show", args=[self.pk])
    

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from templates.shared.timestamped import TimeStampedModel
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser, TimeStampedModel):
  image = models.ImageField(_("프로필사진"), upload_to="users/img", default="users/default/photo.png")
  info = models.CharField(_("소개"), max_length=200, blank=True)

lovely/forms.py
from django import forms
from .models import Lovely

class LovelyForm(forms.ModelForm):
  class Meta:
    model = Lovely
    fields = ['image']
    labels = {
      'image': '사진',
    }

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
  _type = forms.ChoiceField(
    widget=forms.RadioSelect,
    label="게시글 종류",
    choices=Post.POST_TYPES,
    required=True
    )
  class Meta:
    model = Post
    fields = ['title', '_type', 'content', 'image']
    labels = {
      'title': '제목',
      'content': '내용',
      'image': '이미지',
      }
    widgets = {
      'title': forms.TextInput(attrs={
        'class': 'form-control'
        }),
      'content': forms.Textarea(attrs={
        'class': 'form-control'
        }),
    }

accounts/views.py
from django.shortcuts import render, redirect
from users.models import User
from django.contrib import auth


def login(request):
  if request.method == "POST":
    username = request.POST["username"]
    password = request.POST["password"]
    user = auth.authenticate(request, username=username, password=password)
    if user is not None:
      auth.login(request, user)
      return redirect('main')
    else:
      return render(request, 'accounts/login.html', {'error': 'username or password is incorrect.'})
  else:
    return render(request, 'accounts/login.html')


def logout(request):
  return


def signup(request):
  if request.method == "POST":
    if request.POST["password1"] == request.POST["password2"]:
      user = User.objects.create_user(
        username=request.POST.get("username"),
        password=request.POST.get("password1")
      )
      auth.login(request, user)
      return redirect('main')
    return render(request, 'accounts/signup.html')
  return render(request, 'accounts/signup.html')

django_practice/views.py
from django.shortcuts import render


def main(request):
  return render(request, 'main.html')

lovely/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Lovely
import pdb

def main(request):
  context = {
    'lovely': Lovely.objects.all()
  }
  return render(request, 'lovely/main.html', context)


@login_required(login_url= '/accounts/login')
def new(request):
  return render(request, 'lovely/new.html')


@login_required(login_url= '/accounts/login')
def create(request):
  if request.method == "POST":
    image = request.FILES.get('image')
    # Lovely(image = image).save()
    Lovely.objects.create(image = image)
    return redirect('lovely:main')


@login_required(login_url= '/accounts/login')
def delete(request):
  return redirect('main')

maps/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
from .forms import PostForm
from django.contrib.auth.decorators import login_required
import pdb
from django.views.decorators.http import require_POST


# Create your views here.
def main(request):
  context = {
    'posts': Post.objects.all()
  }
  return render(request, 'posts/main.html', context)




@login_required(login_url= '/accounts/login')
def new(request):
  context = {
    'form': PostForm()
  }
  return render(request, 'posts/new.html', context)


@login_required(login_url= '/accounts/login')
@require_POST
def create(request):
  form = PostForm(request.POST, request.FILES or None)
  if form.is_valid():
    form.save()
  return redirect(form.instance)


@login_required(login_url= '/accounts/login')
def show(request, post_id):
  post = get_object_or_404(Post, pk=post_id)
  default_view_count = post.view_count
  post.view_count = default_view_count + 1
  post.save()
  context = {
    'post': post
  }
  return render(request, 'posts/show.html', context)


def edit(request, post_id):
  post = get_object_or_404(Post, pk=post_id)
  context = {
    'post': post,
    'form': PostForm(instance=post)
  }
  return render(request, 'posts/edit.html', context)


@login_required(login_url= '/accounts/login')
@require_POST
def update(request, post_id):
  post = get_object_or_404(Post, pk=post_id)
  # pdb.set_trace()
  form = PostForm(request.POST, request.FILES or None, instance=post) # 그냥 작성하면 create를 해버리기 때문에 instance를 정의해줘서 찾은 post를 이용한다고 명시해줘야 한다.
  # form.save를 하면 새로운 객체를 생성하지만 instance를 적어주면 update해준다라고 알면 될 듯
  if form.is_valid():
    form.save()
  return redirect(post)
    

@login_required(login_url= '/accounts/login')
@require_POST
def delete(request, post_id):
  post = get_object_or_404(Post, pk=post_id)
  post.delete()
  return redirect('main')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <form method="POST" action="{% url 'login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username"><br>
    Password: <input type="password" name="password"><br>
    <input type="submit" value="로그인" class="btn btn-primary">
  </form>
  <a href="{% url 'signup' %}" class="btn btn-outline-primary">회원가입</a>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <form method="POST" action="{% url 'signup' %}">
    {% csrf_token %}
    <label>Username: </label>
    <input type="text" name="username"><br>
    <label>Password: </label>
    <input type="password" name="password1"><br>
    <label>Confirm Password: </label>
    <input type="password" name="password2"><br>

    <input type="submit" class="btn btn-primary" value="sign up">
  </form>
</div>
{% endblock %}

lovely/templates/lovely/main.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1>댕냥스타그램</h1>
  <a href="{% url 'lovely:new' %}">사진 등록</a>

  <div class="row" style="margin-top: 20px;">
    {% for img in lovely %}
      {% if img.image %}
        <div class="col-md-3">
          <img src="{{ img.image.url }}" alt="..." class="img-thumbnail">
        </div>
      {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock %}

lovely/templates/lovely/new.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1>새로운 사진 업로드</h1>
  <form action="{% url 'lovely:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token%}
    <input type='file' name='image'>
    <input type="submit" value="업로드" class="btn btn-primary">
  </form>
</div>
{% endblock %}

posts/templates/posts/_form.html
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="{{ btn_value }}" class="btn btn-outline-primary">

posts/templates/posts/edit.html
{% extends 'base.html' %}
{% include static %}

{% block content %}
<div class="container">
  <h1>글 수정하기</h1>
  <form action="{% url 'posts:update' post.pk %}" method="POST" enctype="multipart/form-data">
    {% include 'posts/_form.html' with form=form btn_value="글 수정" %}
  </form>
</div>
{% endblock %}

posts/templates/posts/main.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1>제훈's Blog</h1>
  <a href="{% url 'posts:new' %}">새 글 쓰기</a>
  <div class="row">
    {% for post in posts %}
      <div class="col-md-4 col-12">
        <div class="card" style="width: 18rem; margin-top:20px;">
          {% if post.image %}
            <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">{{ post.content }}</p>
            <p> {{ post.created_at }}</p>
            <a href="{% url 'posts:show' post.id %}" class="btn btn-primary">태그 이용 이동</a>
            <a href="{{ post.get_absolute_url }}" class="btn btn-primary">변수 이용 이동</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %}
{% include static %}

{% block content %}
<div class="container">
  <h1>새로운 글 쓰기</h1>
  <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
    {% include 'posts/_form.html' with form=form btn_value="글 작성"%}
  </form>
</div>

{% endblock %}

posts/templates/posts/show.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1>게시글 상세페이지</h1>
  <h2>
    제목: {{ post.title }}
  </h2>

  <p>내용: {{ post.content }}</p>

  <p>조회수: {{ post.view_count }}</p>

  <a href="{% url 'posts:edit' post.id %}" class="btn btn-outline-primary">수정</a>
  <a href="#" class="btn btn-outline-danger" data-toggle="modal" data-target="#exampleModal">삭제</a>

  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">정말 삭제하시겠습니까?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
          <form action="{% url 'posts:delete' post.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="삭제" class="btn btn-outline-danger">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href='{% static "css/project.css" %}'>
    <title>Hoon's world</title>
  </head>
  <body>
    {% include 'shared/_navbar.html' %}
    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/main.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1>제훈's 여러가지</h1>
  <div class="row">
    {% include 'shared/_card.html' with title="포스트" content="대충 글 써 놓는 곳" URL="posts:main"%}
    {% include 'shared/_card.html' with title="댕냥이" content="대충 사진 올리는 곳" URL="lovely:main"%}
  </div>
</div>

{% endblock %}

templates/shared/_card.html
<div class="col-md-4 col-12">
  <div class="card" style="width: 18rem; margin-top:20px;">
    <div class="card-body">
      {% if title %}
        <h5 class="card-title">{{ title }}</h5>
      {% endif %}
      {% if content %}
        <p class="card-text">{{ content }}</p>
      {% endif %}
      <a href="{% url URL %}" class="btn btn-primary">이동하기</a>
    </div>
  </div>
</div>

templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">훈's world</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">홈 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'posts:main' %}">포스트</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'lovely:main' %}">댕냥이</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          마이페이지
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if user is not None %}
            <a class="dropdown-item" href="{% url 'login' %}">로그인</a>
            <a class="dropdown-item" href="{% url 'signup' %}">회원가입</a>
          {% else %}
            <a class="dropdown-item" href="{% url 'logout' %}">로그아웃</a>
          {% endif %}
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>